# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        # Adjust target coverage percentage as needed
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 10%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false    # Post comment even if no coverage changes
  require_base: false       # Post comment even without base coverage
  require_head: true        # Must have coverage report to post
  hide_project_coverage: false  # Show project coverage (not just patch)

# Ignore coverage for test files and generated files
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/__tests__/**"
  - "**/dist/**"
  - "coverage/**"
  - "**/*.d.ts"
  - "jest.config.js"
  - ".eslintrc.cjs"
  - "dist-create-package.cjs"