name: Publish Client Package to npm

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version increment type (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Update package version
        run: npm version ${{ github.event.inputs.version_bump }} --no-git-tag-version
      - run: npm run dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
